'use strict';
(()=>{
const $=id=>document.getElementById(id),endpoint='https://incidents-server.oecdai.org/api/v1/incidents/fetch-incidents';let selection=null,generation=0,controller=null;
let countryCatalog=null;
async function countries(){if(!countryCatalog)countryCatalog=(async()=>{const c=new AbortController(),t=setTimeout(()=>c.abort(),15000);try{const response=await fetch('https://incidents-server.oecdai.org/api/v1/incidents/get-countries',{signal:c.signal});if(!response.ok)throw Error('국가 목록 조회 실패');const rows=await response.json();if(!Array.isArray(rows)||!rows.length||rows.some(x=>!/^\w{3}$/.test(x.key)))throw Error('국가 목록 형식 오류');return new Set(rows.map(x=>x.key))}finally{clearTimeout(t)}})().catch(e=>{countryCatalog=null;throw e});return countryCatalog;}
function clear(message,state='info'){$('risk-state').dataset.state=state;$('risk-data').hidden=true;$('risk-state').textContent=message;}
async function load(force=false){const epoch=++generation;controller?.abort();controller=new AbortController();const current=selection;$('risk-country').textContent=current?.name||'국가를 선택하세요';$('risk-code').textContent=current?.code||'';$('risk-refresh').disabled=!current;if(!current)return clear('지도에서 국가를 선택해 주세요.');const code=current.aimCode||current.code;
const now=new Date(),to=[now.getFullYear(),String(now.getMonth()+1).padStart(2,'0'),String(now.getDate()).padStart(2,'0')].join('-'),from='2020-01-01',key='aim-country-v4-'+code+'-'+to;
clear('AIM 정보를 조회하고 있습니다…','loading');$('risk-refresh').disabled=true;
try{const supported=await countries();if(epoch!==generation)return;if(!supported.has(code)){clear('AIM 국가 목록에 이 국가·지역의 조회 항목이 없습니다.');return}let data=null;try{const cached=JSON.parse(sessionStorage.getItem(key)||'null');if(!force&&cached&&Date.now()-cached.fetchedAt<3600000)data=cached;}catch{}
if(!data){const requestController=controller,signal=requestController.signal;const timer=setTimeout(()=>requestController.abort(),25000);try{
async function query(type,limit){const properties_config={principles:[],industries:[],harm_types:[],harm_levels:type?[type]:[],harmed_entities:[],business_functions:[],ai_tasks:[],autonomy_levels:[],languages:[]};const r=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({search_terms:[],and_condition:false,from_date:from,to_date:to,properties_config,order_by:'date',num_results:limit,countries:[code],format:'JSON'}),signal});if(!r.ok)throw Error('AIM 응답 오류 ('+r.status+')');const d=await r.json();if(!Number.isSafeInteger(d.total_results)||d.total_results<0||!Array.isArray(d.incidents))throw Error('AIM 응답 형식이 변경되었습니다.');if(d.incidents.some(x=>x.location?.country_code!==code))throw Error('국가 필터 응답을 확인할 수 없습니다.');return d;}
const [all,incident,hazard]=await Promise.all([query(null,100),query('AI incident',1),query('AI hazard',1)]);
if(incident.incidents.some(x=>!x.properties?.harm_levels?.includes('AI incident'))||hazard.incidents.some(x=>!x.properties?.harm_levels?.includes('AI hazard')))throw Error('사건 분류 필터를 확인할 수 없습니다.');
data={country:{code,name:current.name},records:all.incidents.map(x=>({id:String(x.id),title:String(x.title||''),summary:typeof x.summary==='string'?x.summary:'',date:String(x.date||''),n_articles:Number.isSafeInteger(x.n_articles)?x.n_articles:null,properties:Object.fromEntries(['harm_levels','harm_types','industries','harmed_entities','principles','ai_tasks'].map(k=>[k,Array.isArray(x.properties?.[k])?x.properties[k].filter(v=>typeof v==='string'):[]]))})),total:all.total_results,incidents:incident.total_results,hazards:hazard.total_results,sample:all.incidents.length,articles:all.incidents.every(x=>Number.isSafeInteger(x.n_articles)&&x.n_articles>=0)?all.incidents.reduce((n,x)=>n+x.n_articles,0):null,from,to,fetchedAt:Date.now()};try{sessionStorage.setItem(key,JSON.stringify(data));}catch{}
}finally{clearTimeout(timer)}}
if(epoch!==generation)return;
const fmt=n=>n.toLocaleString('ko-KR');$('aim-total').textContent=fmt(data.total);$('aim-incidents').textContent=fmt(data.incidents);$('aim-hazards').textContent=fmt(data.hazards);$('aim-articles').textContent=data.articles===null?'미제공':fmt(data.articles);$('article-label').textContent='최근 '+data.sample+'건의 관련 기사 수 합계';$('risk-period').textContent=data.from+' — '+data.to;
const reconciled=data.incidents+data.hazards===data.total;$('incident-bar').style.width=(data.total?data.incidents/data.total*100:0)+'%';$('hazard-bar').style.width=(data.total?data.hazards/data.total*100:0)+'%';document.querySelector('.risk-bar').hidden=!reconciled;$('risk-reconciliation').textContent=reconciled?'사건과 잠재위험을 구분한 AIM 검색 건수입니다.':'분류별 합계가 전체와 다릅니다. 갱신 시점 또는 분류 중복 여부를 확인해야 합니다.';$('risk-updated').textContent='조회: '+new Date(data.fetchedAt).toLocaleString('ko-KR');$('risk-data').hidden=false;$('risk-state').dataset.state=data.total===0?'empty':'success';$('risk-state').textContent=data.total===0?'조회 기간에 해당하는 기록이 없습니다.':current.name+' · AIM 조회 결과';document.dispatchEvent(new CustomEvent('aim:loaded',{detail:data}));
}catch(e){if(epoch===generation)clear('자료를 불러오지 못했습니다. 다시 조회해 주세요.','error');}finally{if(epoch===generation)$('risk-refresh').disabled=false;}}
document.addEventListener('gis:country-selected',e=>{if(selection&&selection.code===e.detail?.code)return;selection=e.detail;load();});$('risk-refresh').addEventListener('click',()=>load(true));$('risk-refresh').disabled=true;
})();