'use strict';
(()=>{
const $=id=>document.getElementById(id),root=$('explore-dialog'),explorer=root.querySelector('.explorer'),make=(tag,cls,text)=>{const n=document.createElement(tag);n.className=cls;if(text)n.textContent=text;return n};
const intro=make('div','explore-intro');intro.append(explorer.querySelector('.explorer-heading'));const note=explorer.querySelector('.scope-note');note.textContent='최근 기록을 분류별로 살펴봅니다. 한 기록이 여러 분류에 포함될 수 있습니다.';intro.append(note);explorer.prepend(intro);
const tabs=make('div','explore-mobile-tabs');tabs.setAttribute('role','group');tabs.setAttribute('aria-label','탐색 화면');const filterButton=make('button','','분류 선택'),resultButton=make('button','','관련 기록');tabs.append(filterButton,resultButton);intro.after(tabs);
const columns=make('div','explore-columns'),filters=make('section','explore-filters'),results=make('section','explore-results');filters.setAttribute('aria-label','사건·잠재위험 분류 선택');results.setAttribute('aria-label','선택한 분류의 기록');columns.append(filters,results);tabs.after(columns);
filters.append($('type-filters'),explorer.querySelector('.classification-chips'));const hint=make('p','selection-hint','분류를 누르면 관련 기록이 바뀝니다.');filters.append(hint,$('category-bars'));
const resultHead=make('div','explore-result-head'),title=make('h3','','관련 기록');resultHead.append(title,$('filter-caption').parentElement);results.append(resultHead);const question=$('interest-question');results.append(question);const trend=make('section','explore-trend');trend.setAttribute('aria-label','선택한 기록의 월별 분포');trend.append(explorer.querySelector('.trend-heading'),$('monthly-chart'));results.append(trend);
const list=make('div','explore-record-scroll');list.tabIndex=0;list.setAttribute('aria-label','관련 기록 목록');list.append(explorer.querySelector('.records-heading'),$('risk-records'));results.append(list,explorer.querySelector('.record-pagination'));
function view(value){root.dataset.pane=value;filterButton.setAttribute('aria-pressed',String(value==='filters'));resultButton.setAttribute('aria-pressed',String(value==='results'))}view('filters');filterButton.onclick=()=>view('filters');resultButton.onclick=()=>view('results');
function update(){const count=window.aiRiskI18n?.source($('record-count')) || $('record-count').textContent;resultButton.textContent='관련 기록 '+count;const category=window.aiRiskI18n?.source($('category-bars').querySelector('[aria-pressed=true] .category-bar-label span')) || $('category-bars').querySelector('[aria-pressed=true] .category-bar-label span')?.textContent;title.textContent=category?category+' · 관련 기록':'전체 분류 · 관련 기록';list.scrollTop=0;}
new MutationObserver(update).observe($('filter-caption'),{childList:true,characterData:true,subtree:true});$('category-bars').addEventListener('click',e=>{if(!e.target.closest('button'))return;update();if(matchMedia('(max-width: 760px)').matches)view('results')});
filters.addEventListener('click',e=>{if(e.target.closest('.classification-chip,#type-filters button')){$('category-bars').scrollTop=0;update()}});$('clear-category').addEventListener('click',update);document.addEventListener('aim:loaded',()=>{update();view('filters')});
})();
