'use strict';
(()=>{
const $=id=>document.getElementById(id);let current=null,selected=null,lastFocus=null;
const make=(tag,cls,text)=>{const n=document.createElement(tag);if(cls)n.className=cls;if(text!==undefined)n.textContent=text;return n};
const sourceDetails=make('details','source-details');sourceDetails.append(make('summary','','출처·집계 기준'));const panel=$('risk-panel');for(const n of [...panel.children])if(n.matches('.risk-note,.risk-sources'))sourceDetails.append(n);panel.append(sourceDetails);
const dialogs=[];function dialog(id,title){const d=make('dialog','journey-dialog');d.id=id;const head=make('header','journey-dialog-head');const heading=make('h2','',title);heading.id=id+'-title';d.setAttribute('aria-labelledby',heading.id);const close=make('button','journey-close','닫기');close.type='button';close.onclick=()=>d.close();head.append(heading,close);d.append(head);d.addEventListener('cancel',e=>e.preventDefault());d.addEventListener('close',()=>d.returnFocus?.isConnected&&d.returnFocus.focus());document.body.append(d);dialogs.push(d);return d}
function open(d){d.returnFocus=document.activeElement;d.showModal();d.querySelector('.journey-close').focus()}
const explorer=document.querySelector('.explorer'),explore=dialog('explore-dialog','02 · 관심 분야에서 사건까지');explore.append(explorer);const interests=make('div','interest-prompt');interests.innerHTML='<label for="interest-mode">어떤 관점이 궁금하세요?</label><select id="interest-mode"><option value="harm_types">전체 피해 살펴보기</option><option value="industries">내 산업·업무 분야</option><option value="harmed_entities">영향받는 사람들</option><option value="principles">권리와 안전 원칙</option><option value="ai_tasks">AI 기술의 쓰임</option></select><small>언제든 바꿀 수 있습니다.</small>';explorer.prepend(interests);$('interest-mode').onchange=e=>{$('classification').value=e.target.value;$('classification').dispatchEvent(new Event('change'));};$('classification').addEventListener('change',()=>{$('interest-mode').value=$('classification').value;});
const overview=make('section','overview-categories');overview.innerHTML='<div class="overview-heading"><h3>어떤 피해가 보고됐을까요?</h3><span id="overview-scope"></span></div><div id="overview-top"></div><button id="explore-open" class="journey-primary">내 관심 분야로 살펴보기</button><p class="overview-note">최신 수신 기록의 상위 분류 · 복수 분류 포함</p>';$('risk-updated').before(overview);$('explore-open').onclick=()=>open(explore);
const detail=dialog('event-dialog','03 · 사건과 근거 확인'),detailBody=make('div','detail-body');detail.append(detailBody);
const community=dialog('community-dialog','04 · 함께 논의할 질문'),body=make('div','discussion-body');body.innerHTML='<p class="eyebrow">대한민국에서 시작하는 글로벌 대화</p><h3>위험을 줄이는 일에는<br>여러 사람의 경험이 필요합니다.</h3><p>당사자의 경험, 기술적 검토, 정책적 대응을 하나의 질문으로 연결해 보세요.</p><label for="discussion-question">함께 논의하고 싶은 질문</label><textarea id="discussion-question" rows="4"></textarea><div class="discussion-roles"><span>당사자 · 경험</span><span>연구자 · 검증</span><span>정책 실무자 · 대응</span></div><button id="discussion-copy" class="journey-primary">질문과 출처 복사</button><p id="discussion-status" role="status"></p><small>현재는 논의 초안을 만드는 프로토타입입니다. 입력은 서버에 전송되지 않으며 커뮤니티 가입 기능은 아직 없습니다.</small>';community.append(body);
function discuss(record){selected=record||null;$('discussion-question').value=record?'이 사건에서 어떤 피해를 확인할 수 있으며, 비슷한 피해를 줄이기 위해 어떤 대응과 참여자가 필요할까요?':'대한민국의 AI 사건·잠재위험을 함께 살펴볼 때, 우선 확인하고 대응해야 할 문제는 무엇일까요?';$('discussion-status').textContent='';open(community)}
$('community-open').onclick=()=>discuss(null);$('discussion-copy').onclick=async()=>{const text=$('discussion-question').value.trim()+'\n\n참고: '+(selected?selected.title+'\nhttps://oecd.ai/en/incidents/'+encodeURIComponent(selected.id):'OECD AIM · https://oecd.ai/en/incidents')+'\nAIM은 언론 보도 기반 AI 분류이며 사실 확인을 대체하지 않습니다.';try{await navigator.clipboard.writeText(text);$('discussion-status').textContent='질문과 출처를 복사했습니다. 함께 논의할 사람에게 공유해 보세요.'}catch{$('discussion-status').textContent='복사가 허용되지 않았습니다. 질문을 선택해 직접 복사해 주세요.'}};
function showRecord(id){const r=current?.records.find(r=>r.id===id);if(!r)return;detailBody.replaceChildren();detailBody.append(make('p','eyebrow',r.date+' · AIM 원문'),make('h3','',r.title),make('p','detail-summary',r.summary||'이 기록의 요약은 제공되지 않았습니다. AIM 원문에서 근거를 확인해 주세요.'));const facts=make('div','detail-facts');for(const [title,key]of [['피해 유형','harm_types'],['산업 분야','industries'],['피해 대상','harmed_entities']]){const group=make('div','');group.append(make('strong','',title),make('p','',(r.properties[key]||[]).map(v=>window.aimLabel?.(v)||v).join(' · ')||'미분류'));facts.append(group)}detailBody.append(facts,make('p','scope-note','제목·요약은 AIM 원문입니다. AI가 생성한 분류와 요약은 원출처를 통해 확인해 주세요.'));const link=make('a','journey-link','AIM에서 원문과 보도 확인');link.href='https://oecd.ai/en/incidents/'+encodeURIComponent(r.id);link.target='_blank';link.rel='noopener';const action=make('button','journey-primary','이 사건의 검토 초안 만들기');action.onclick=()=>{for(const d of [...dialogs].reverse())if(d.open)d.close();document.dispatchEvent(new CustomEvent('risk:review',{detail:r}));};detailBody.append(link,action);open(detail)}
$('risk-records').addEventListener('click',e=>{const link=e.target.closest('a.record-title');if(!link||e.ctrlKey||e.metaKey||e.shiftKey||e.altKey)return;e.preventDefault();showRecord(decodeURIComponent(link.href.split('/').pop()))});
document.addEventListener('aim:loaded',e=>{current=e.detail;document.querySelector('#explore-dialog-title').textContent='02 · '+current.country.name+' · 관심 분야에서 사건까지';const counts=new Map();for(const r of current.records)for(const v of new Set(r.properties.harm_types))counts.set(v,(counts.get(v)||0)+1);$('overview-scope').textContent='최신 '+current.records.length+'건';const top=$('overview-top');top.replaceChildren();for(const [name,count]of [...counts].sort((a,b)=>b[1]-a[1]).slice(0,3)){const b=make('button','overview-row');b.append(make('span','',window.aimLabel?.(name)||name),make('strong','',count+'건'));b.style.setProperty('--share',(count/current.records.length*100)+'%');b.onclick=()=>{$('classification').value='harm_types';$('classification').dispatchEvent(new Event('change'));$('type-filters').querySelector('[data-type="all"]').click();[...$('category-bars').children].find(x=>x.getAttribute('aria-label')===(window.aimLabel?.(name)||name)+' '+count+'건')?.click();open(explore)};top.append(b)}if(!counts.size)top.append(make('p','scope-note','수신 기록에 피해 분류가 없습니다.'));});
document.addEventListener('gis:country-selected',()=>{for(const d of dialogs)if(d.open)d.close();});
})();
