'use strict';
(()=>{
const $=id=>document.getElementById(id),make=(tag,cls,text)=>{const e=document.createElement(tag);if(cls)e.className=cls;if(text!==undefined)e.textContent=text;return e;};
const base='https://api.oecdai.org',states=[['Active','활동 중','Active','active'],['Proposed or under development','제안·개발 중','In development','proposed'],['Inactive – initiative complete','종료','Completed','complete'],['Inactive – initiative not initiated','미착수','Not started','not-started']];
const categories={'AI policy initiatives, programmes and projects':['정책·사업','Programmes and projects'],'Regulations, guidelines and standards':['규제·지침·표준','Regulations and guidance'],'National – AI governance bodies or mechanisms':['거버넌스 기구·체계','Governance bodies'],'National – Strategy':['국가 전략','National strategies'],'AI Policy Frameworks and Initiatives (intergovernmental or supranational)':['국제 정책 체계','International frameworks'],'AI Governance Bodies and Mechanisms (intergovernmental or supranational)':['국제 거버넌스','International governance']};
const sectors={'Science & technology':'과학기술','Public sector':'공공부문','Other':'기타','Industry & entrepreneurship':'산업·기업가정신','Public governance':'공공 거버넌스','Innovation':'혁신','Health':'보건','Agriculture':'농업','Education':'교육','Transport':'교통','Digital Economy':'디지털 경제','Economy':'경제','Finance and insurance':'금융·보험','Environment':'환경','Defence':'국방','Investment':'투자','Inclusive development':'포용적 발전'};
const en=()=>window.aiRiskI18n?.language!=='ko',L=(ko,english)=>en()?english:ko,categoryLabel=v=>categories[v]?.[en()?1:0]||v||L('미분류','Unclassified'),statusLabel=v=>{const s=states.find(x=>x[0]===v);return s?s[en()?2:1]:v||L('미입력','Not supplied')},sectorLabel=v=>en()?v:sectors[v]||v;
let selection=null,current=null,generation=0,controller=null,catalog=null,catalogPromise=null,statusFilter='',categoryFilter='',sectorFilter='',page=0,detailRecord=null;
const cache=new Map();
function safeUrl(value){try{const u=new URL(value);return ['http:','https:'].includes(u.protocol)?u.href:null}catch{return null}}
function normalize(x,country){if(!Number.isSafeInteger(x.id)||x.gaiinCountry?.code!==country.code||typeof x.englishName!=='string')throw Error('Invalid policy country or identifier');return{id:x.id,englishName:x.englishName,originalName:typeof x.originalName==='string'?x.originalName:'',slug:typeof x.slug==='string'?x.slug:'',description:typeof x.description==='string'?x.description:'',status:typeof x.status==='string'?x.status:'',category:typeof x.category==='string'?x.category:'',startYear:Number.isInteger(x.startYear)?x.startYear:null,endYear:Number.isInteger(x.endYear)?x.endYear:null,binding:typeof x.extentBinding==='string'?x.extentBinding:null,organisation:typeof x.responsibleOrganisation==='string'?x.responsibleOrganisation:null,website:safeUrl(x.website),updatedAt:typeof x.updatedAt==='string'?x.updatedAt:null,sectors:(x.targetSectors||[]).filter(v=>typeof v.name==='string').map(v=>v.name),principles:(x.principles||[]).filter(v=>typeof v.name==='string').map(v=>v.name),tags:(x.tags||[]).filter(v=>typeof v.name==='string').map(v=>v.name),type:x.initiativeType?.name||null};}
async function countryList(){
if(catalog)return catalog;
if(!catalogPromise)catalogPromise=(async()=>{
 const abort=new AbortController(),timer=setTimeout(()=>abort.abort(),30000);
 try{
  const rows=[];let lastPage=1,total=null;
  for(let page=1;page<=lastPage;page++){
   const response=await fetch(base+'/countries?page='+page,{signal:abort.signal,credentials:'omit'});
   if(!response.ok)throw Error('Country lookup failed');
   const data=await response.json();
   if(Array.isArray(data)){if(page!==1)throw Error('Country format changed');rows.push(...data);break}
   if(!Array.isArray(data.data)||!Number.isSafeInteger(data.total)||data.total<0||!Number.isInteger(data.lastPage)||data.lastPage<1||data.lastPage>100||data.currentPage!==page||(total!==null&&total!==data.total))throw Error('Country pagination changed');
   total=data.total;lastPage=data.lastPage;rows.push(...data.data);
  }
  if(total!==null&&(rows.length!==total||new Set(rows.map(x=>x.id)).size!==total))throw Error('Incomplete country results');
  const countries=rows.filter(x=>Number.isSafeInteger(x.id)&&/^[A-Z]{3}$/.test(x.code)&&typeof x.name==='string').map(({id,code,name})=>({id,code,name}));
  if(!countries.length)throw Error('Country format changed');
  catalog=countries;return catalog;
 }finally{clearTimeout(timer)}
})().catch(e=>{catalogPromise=null;throw e});
return catalogPromise;
}
function setState(ko,english,state){$('policy-state').textContent=L(ko,english);$('policy-state').dataset.noTranslate='true';$('policy-state').dataset.state=state;}
let stateKey='initial';function renderState(){const labels={initial:['기본 국가를 확인하고 있습니다…','Finding your starting country…','loading'],none:['지도에서 국가를 선택해 주세요.','Choose a country on the map.','info'],loading:['정책 정보를 조회하고 있습니다…','Loading policy records…','loading'],unsupported:['OECD 정책 목록에서 이 국가·지역을 찾지 못했습니다.','This country or territory is not listed in the OECD policy catalogue.','empty'],error:['정책 정보를 불러오지 못했습니다. 다시 조회해 주세요.','Could not load policy records. Please try again.','error'],empty:['등록된 정책이 없습니다.','No policy records were found.','empty'],ready:['OECD 정책 등록 현황','OECD policy inventory','success']};setState(...labels[stateKey]);}
function countryName(){return current?(en()?(current.country.code==='KOR'?'South Korea':current.country.name):selection?.name||current.country.name):selection?(en()?(catalog?.find(x=>x.code===(selection.aimCode||selection.code))?.name||selection.code):selection.name):L('국가를 선택하세요','Choose a country')}
function policyTitle(record){return !en()&&record.originalName?record.originalName:record.englishName}
function recordUrl(record){return record.slug?'https://oecd.ai/en/dashboards/policy-initiatives/'+encodeURIComponent(record.slug):'https://oecd.ai/en/dashboards/policy-initiatives?countryIds='+current.country.id}
function counts(values){const map=new Map();for(const v of values)map.set(v,(map.get(v)||0)+1);return [...map].sort((a,b)=>b[1]-a[1]);}
function modal(id,title){const d=make('dialog','journey-dialog policy-dialog');d.id=id;d.dataset.noTranslate='true';const head=make('header','journey-dialog-head'),h=make('h2','',title);h.id=id+'-title';d.setAttribute('aria-labelledby',h.id);const close=make('button','journey-close',L('닫기','Close'));close.type='button';close.onclick=()=>d.close();head.append(h,close);d.append(head);d.addEventListener('cancel',e=>e.preventDefault());d.addEventListener('close',()=>{if(d.returnFocus?.isConnected)d.returnFocus.focus({preventScroll:true})});document.body.append(d);return d;}
const explorer=modal('policy-dialog',''),body=make('div','policy-explorer-body');explorer.append(body);const filters=make('div','policy-filters'),resultMeta=make('p','policy-result-meta'),list=make('div','policy-list');list.tabIndex=0;const pagination=make('div','policy-pagination');body.append(filters,resultMeta,list,pagination);
const detail=modal('policy-detail-dialog','');detail.classList.add('policy-detail');const detailBody=make('div','policy-detail-body');detail.append(detailBody);
function open(d){d.returnFocus=document.activeElement;d.showModal();d.querySelector('.journey-close').focus()}
function showExplorer(filter='',category=''){statusFilter=filter;categoryFilter=category;sectorFilter='';page=0;renderExplorer();open(explorer)}
function renderOverview(){renderState();$('policy-country').textContent=countryName();$('policy-country').dataset.noTranslate='true';$('policy-code').textContent=selection?.code||'';if(!current)return;const rows=current.records;$('policy-total').textContent=String(rows.length);const box=$('policy-status-counts');box.replaceChildren();const bar=$('policy-status-bar');bar.replaceChildren();for(const [status,ko,english,color]of states){const count=rows.filter(x=>x.status===status).length;const b=make('button','');b.type='button';b.dataset.noTranslate='true';b.append(make('span','',L(ko,english)),make('strong','',String(count)));b.onclick=()=>showExplorer(status);box.append(b);if(count){const piece=make('span','');piece.dataset.status=color;piece.style.width=(count/rows.length*100)+'%';bar.append(piece)}}const unknown=rows.filter(x=>!states.some(s=>s[0]===x.status)).length;if(unknown){const b=make('button','');b.dataset.noTranslate='true';b.append(make('span','',L('기타·미입력','Other / not supplied')),make('strong','',String(unknown)));b.onclick=()=>showExplorer('__other');box.append(b)}
const types=$('policy-type-counts');types.replaceChildren();for(const [category,count]of counts(rows.map(x=>x.category))){const b=make('button','policy-type-row');b.dataset.noTranslate='true';b.append(make('span','',categoryLabel(category)),make('strong','',String(count)));b.onclick=()=>showExplorer('',category);types.append(b)}$('policy-updated').textContent=L('조회: ','Retrieved: ')+new Date(current.fetchedAt).toLocaleString(en()?'en-GB':'ko-KR');$('policy-updated').dataset.noTranslate='true';$('policy-source').href='https://oecd.ai/en/dashboards/policy-initiatives?countryIds='+current.country.id;$('policy-explore').disabled=false;}
function rowChoices(ko,english,values,selected,change,label){const row=make('div','policy-filter-row');row.append(make('strong','',L(ko,english)));const choices=make('div','policy-filter-options');choices.setAttribute('role','group');choices.setAttribute('aria-label',L(ko,english));for(const value of ['',...values]){const b=make('button','ds-chip',value?label(value):L('전체','All'));b.setAttribute('aria-pressed',String(value===selected));b.onclick=()=>{change(value);page=0;renderExplorer()};choices.append(b)}row.append(choices);return row;}
function renderExplorer(){if(!current)return;$('policy-dialog-title').textContent=countryName()+L(' · 정책 현황',' · Policy landscape');explorer.querySelector('.journey-close').textContent=L('닫기','Close');filters.replaceChildren();filters.append(rowChoices('상태','Status',[...new Set(current.records.map(x=>x.status).filter(Boolean))],statusFilter,v=>statusFilter=v,statusLabel));filters.append(rowChoices('유형','Category',[...new Set(current.records.map(x=>x.category).filter(Boolean))],categoryFilter,v=>categoryFilter=v,categoryLabel));const sectorValues=[...new Set(current.records.flatMap(x=>x.sectors))];filters.append(rowChoices('분야','Sector',sectorValues,sectorFilter,v=>sectorFilter=v,sectorLabel));
const rows=current.records.filter(x=>(!statusFilter||(statusFilter==='__other'?!states.some(s=>s[0]===x.status):x.status===statusFilter))&&(!categoryFilter||x.category===categoryFilter)&&(!sectorFilter||x.sectors.includes(sectorFilter)));const pages=Math.max(1,Math.ceil(rows.length/6));page=Math.max(0,Math.min(page,pages-1));resultMeta.textContent=L('검색 결과 '+rows.length+'건 / 전체 '+current.records.length+'건','Showing '+rows.length+' of '+current.records.length+' records');list.setAttribute('aria-label',L('정책 목록','Policy records'));list.replaceChildren();for(const record of rows.slice(page*6,page*6+6)){const card=make('article','policy-record'),b=make('button','',policyTitle(record));b.onclick=()=>{detailRecord=record;renderDetail();open(detail)};card.append(make('p','',statusLabel(record.status)+' · '+(record.startYear??L('연도 미입력','Year not supplied'))),b,make('p','',categoryLabel(record.category)),make('p','',record.sectors.map(sectorLabel).join(' · ')||L('분야 미입력','Sector not supplied')));list.append(card)}if(!rows.length)list.append(make('p','ds-muted',L('조건에 맞는 정책이 없습니다. 필터를 변경해 주세요.','No policies match these filters. Try a different selection.')));list.scrollTop=0;pagination.replaceChildren();for(const [direction,label]of [[-1,L('이전','Previous')],[1,L('다음','Next')]]){const b=make('button','ds-quiet',label);b.disabled=direction<0?page===0:page===pages-1;b.onclick=()=>{page+=direction;renderExplorer()};if(direction===1)pagination.append(make('span','',(page+1)+' / '+pages));pagination.append(b)}}
function renderDetail(){const record=detailRecord;if(!record)return;$('policy-detail-dialog-title').textContent=L('정책과 근거 확인','Policy and evidence');detail.querySelector('.journey-close').textContent=L('닫기','Close');detailBody.replaceChildren();detailBody.append(make('h3','',policyTitle(record)));if(!en()&&record.originalName)detailBody.append(make('p','ds-muted',record.englishName));detailBody.append(make('p','',record.description||L('요약이 제공되지 않았습니다. OECD 원문을 확인해 주세요.','No summary is available. Check the OECD record.')));const facts=make('dl','policy-facts');const binding=record.binding===null?L('미입력 · 원문 확인 필요','Not supplied · check the source'):record.binding==='Non-binding'?L('비구속적','Non-binding'):record.binding;
for(const [label,value]of [[L('상태','Status'),statusLabel(record.status)],[L('정책 유형','Category'),categoryLabel(record.category)],[L('기간','Period'),String(record.startYear??L('미입력','Not supplied'))+(record.endYear?' – '+record.endYear:'')],[L('법적 구속력','Legally binding'),binding],[L('담당 기관','Responsible organisation'),record.organisation],[L('세부 유형','Instrument'),record.type],[L('대상 분야','Target sectors'),record.sectors.map(sectorLabel).join(' · ')],[L('AI 원칙','AI principles'),record.principles.join(' · ')],[L('AI 주제','AI topics'),record.tags.join(' · ')]]){const cell=make('div','');cell.append(make('dt','',label),make('dd','',value||L('미입력','Not supplied')));facts.append(cell)}detailBody.append(facts,make('p','ds-muted',L('상태는 OECD 등록 정보이며 법률 시행 여부와 다를 수 있습니다. 요약과 분류는 원문을 확인해 주세요.','Status reflects the OECD inventory and may differ from a law’s effective status. Check the source for the summary and classifications.')));const links=make('div','policy-detail-links');for(const [label,url]of [[L('OECD 정책 원문 보기','View OECD policy record'),recordUrl(record)],[L('공식 출처 보기','View linked source'),record.website]])if(url){const a=make('a','journey-link',label);a.href=url;a.target='_blank';a.rel='noopener';links.append(a)}detailBody.append(links);const action=make('button','journey-primary',L('이 정책에 정보·질문 보태기','Add information or a question about this policy'));action.onclick=()=>{for(const d of [detail,explorer])if(d.open){d.returnFocus=null;d.close()}document.dispatchEvent(new CustomEvent('risk:review',{detail:{title:policyTitle(record),sourceUrl:record.website||recordUrl(record),country:{code:current.country.code,name:selection?.name||current.country.name},properties:{},kind:'policy'}}))};detailBody.append(action)}
async function load(force=false){const epoch=++generation;controller?.abort();controller=new AbortController();current=null;document.dispatchEvent(new CustomEvent("policy:invalidated"));$('policy-data').hidden=true;$('policy-explore').disabled=true;$('policy-refresh').disabled=!selection;$('policy-source').href='https://oecd.ai/en/dashboards/policy-initiatives';$('policy-updated').textContent='';for(const d of [detail,explorer])if(d.open){d.returnFocus=null;d.close()}detailRecord=null;stateKey=selection?'loading':'none';renderOverview();if(!selection)return;$('policy-refresh').disabled=true;const selected=selection;try{const countries=await countryList();if(epoch!==generation)return;const country=countries.find(x=>x.code===(selected.aimCode||selected.code));if(!country){stateKey='unsupported';renderOverview();return}const previous=cache.get(country.code);if(!force&&previous&&Date.now()-previous.fetchedAt<1800000)current=previous;else{const activeController=controller,timer=setTimeout(()=>activeController.abort(),30000);try{let total=null,lastPage=1,records=[];for(let n=1;n<=lastPage;n++){const url=new URL(base+'/policy-initiatives/public');url.searchParams.set('countryIds',country.id);url.searchParams.set('page',n);const response=await fetch(url,{signal:activeController.signal,credentials:'omit'});if(!response.ok)throw Error('Policy request failed');const d=await response.json();if(!Array.isArray(d.data)||!Number.isSafeInteger(d.total)||d.total<0||!Number.isInteger(d.lastPage)||d.lastPage<1||d.lastPage>100||d.currentPage!==n||(total!==null&&total!==d.total))throw Error('Policy pagination changed');total=d.total;lastPage=d.lastPage;records.push(...d.data.map(x=>normalize(x,country)))}if(records.length!==total||new Set(records.map(x=>x.id)).size!==total)throw Error('Incomplete policy results');if(epoch!==generation)return;current={country,records,fetchedAt:Date.now()};cache.set(country.code,current)}finally{clearTimeout(timer)}}if(epoch!==generation)return;stateKey=current.records.length?'ready':'empty';$('policy-data').hidden=false;renderOverview();document.dispatchEvent(new CustomEvent('policy:loaded',{detail:{country:current.country,total:current.records.length}}))}catch(e){if(epoch===generation){current=null;stateKey='error';renderOverview()}}finally{if(epoch===generation)$('policy-refresh').disabled=false}}
window.aiRiskPolicy={snapshot:()=>current,openRecord:record=>{detailRecord=record;renderDetail();detailBody.lastElementChild.hidden=true;open(detail)}};
$('policy-explore').onclick=()=>showExplorer();$('policy-refresh').onclick=()=>load(true);document.addEventListener('gis:country-selected',event=>{selection=event.detail;load()});let lastLanguage=document.documentElement.lang;new MutationObserver(()=>{if(document.documentElement.lang===lastLanguage)return;lastLanguage=document.documentElement.lang;renderOverview();if(explorer.open)renderExplorer();if(detail.open)renderDetail()}).observe(document.documentElement,{attributes:true,attributeFilter:['lang']});
const entry=document.querySelector('.community-entry');new ResizeObserver(()=>{if(matchMedia('(min-width:701px)').matches)document.documentElement.style.setProperty('--entry-height',entry.getBoundingClientRect().height+'px')}).observe(entry);
})();
