'use strict';
(()=>{
const make=(tag,cls,text)=>{const el=document.createElement(tag);if(cls)el.className=cls;if(text!==undefined)el.textContent=text;return el},L=(ko,en)=>window.aiRiskI18n?.language==='ko'?ko:en;
let incident=null,chosen=null,stage=2,query='',filter='all',returnFocus=null;
const checks=new Set(['coverage','implementation','effect']);
const questions={coverage:['이 정책이 사건의 피해 유형과 피해 당사자를 실제로 보호하는가? 적용 조항과 범위를 확인하고 싶습니다.','Does this policy cover the harm and people affected by this incident? Which provisions apply?'],implementation:['정책이 실제로 시행·집행되고 있는가? 시행일, 담당 기관과 집행 자료를 확인하고 싶습니다.','Is the policy being implemented and enforced? What dates, responsible bodies and implementation evidence can we verify?'],effect:['피해를 줄였다는 근거가 있는가? 평가 보고서와 성과 자료를 확인하고 싶습니다.','Is there evidence that the policy reduces harm? What evaluations or outcome data are available?']};
const dialog=make('dialog','journey-dialog response-dialog');dialog.id='response-dialog';dialog.dataset.noTranslate='true';dialog.setAttribute('aria-labelledby','response-title');dialog.addEventListener('cancel',e=>e.preventDefault());dialog.addEventListener('close',()=>{if(returnFocus?.isConnected)returnFocus.focus({preventScroll:true})});document.body.append(dialog);
const head=make('header','journey-dialog-head'),title=make('h2');title.id='response-title';const close=make('button','journey-close');close.onclick=()=>dialog.close();head.append(title,close);const body=make('div','response-body'),footer=make('footer','response-footer');dialog.append(head,body,footer);
const snapshot=()=>{const s=window.aiRiskPolicy?.snapshot();return s&&s.country.code===(incident?.country?.aimCode||incident?.country?.code)?s:null};
const source=r=>r.slug?'https://oecd.ai/en/dashboards/policy-initiatives/'+encodeURIComponent(r.slug):'https://oecd.ai/en/dashboards/policy-initiatives';
const incidentUrl=()=> 'https://oecd.ai/en/incidents/'+encodeURIComponent(incident.id);
const policyTitle=r=>window.aiRiskI18n?.language==='ko'&&r.originalName?r.originalName:r.englishName;
const normal=v=>v.toLowerCase().replace(/[^\p{L}\p{N}]/gu,'');
function matches(r){const principles=(incident.properties?.principles||[]).map(normal);return r.principles.filter(x=>principles.includes(normal(x)))}
function link(label,url){const a=make('a','journey-link',label);a.href=url;a.target='_blank';a.rel='noopener';return a}
function button(label,action,cls='ds-secondary'){const b=make('button',cls,label);b.type='button';b.onclick=action;return b}
function render(){title.textContent=L('이 사건에서 함께 조사할 질문까지','From this incident to a shared inquiry');close.textContent=L('닫기','Close');body.replaceChildren();footer.replaceChildren();const progress=make('ol','response-steps');for(const [i,ko,en]of [[1,'사건 발견','Incident'],[2,'대응 정책 확인','Policy'],[3,'부족한 근거 찾기','Evidence gaps'],[4,'함께 조사하기','Investigate together']]){const item=make('li','',i+' · '+L(ko,en));if(i===stage)item.setAttribute('aria-current','step');progress.append(item)}body.append(progress);const context=make('section','response-context');context.append(make('span','eyebrow',window.aiRiskI18n?.language==='ko'?incident.country.name:(snapshot()?.country.name||incident.country.code)),make('h3','',incident.title),link(L('사건 원문 확인','Read the incident source'),incidentUrl()));body.append(context);if(stage===2)renderPolicies();else renderGaps();}
function renderPolicies(){body.append(make('h3','',L('이 위험에 어떤 정책이 대응할 수 있을까요?','Which policies might address this risk?')),make('p','ds-muted',L('같은 국가의 등록 정책입니다. 공통 AI 원칙은 탐색 단서이며, 이 사건에 대한 적용이나 효과가 검증된 연결은 아닙니다.','These policies are registered for the same country. Shared AI principles are discovery clues, not verified evidence of coverage or effectiveness.')));
const s=snapshot();if(!s){body.append(make('p','response-empty',L('이 국가의 정책 정보를 아직 확인하지 못했습니다. 조회 후 다시 확인하거나, 정책 찾기를 조사 질문으로 남길 수 있습니다.','Policy data for this country is not available yet. Retry the lookup or make finding a relevant policy your research question.')),button(L('정책 다시 조회','Retry policy lookup'),()=>document.getElementById('policy-refresh').click()));}else{
const controls=make('div','response-search');const lab=make('label','',L('정책 찾기','Find a policy'));const input=make('input','ds-input');input.id='response-search';input.value=query;input.placeholder=L('정책명·설명에서 검색','Search policy titles and descriptions');lab.htmlFor=input.id;controls.append(lab,input);const group=make('div','response-filters');for(const [v,ko,en]of [['all','국가 정책 전체','All country policies'],['shared','공통 원칙이 있는 정책','Shared principles']]){const b=button(L(ko,en),()=>{filter=v;render()},'ds-chip');b.setAttribute('aria-pressed',String(filter===v));group.append(b)}controls.append(group);body.append(controls);const list=make('div','response-policy-list');body.append(list);const renderRows=()=>{list.replaceChildren();const rows=s.records.filter(r=>(filter!=='shared'||matches(r).length)&&[r.englishName,r.originalName,r.description].join(' ').toLowerCase().includes(query.toLowerCase())).sort((a,b)=>matches(b).length-matches(a).length);list.append(make('p','ds-muted',L(rows.length+'건 · 전체 '+s.records.length+'건',rows.length+' of '+s.records.length+' records')));if(!rows.length)list.append(make('p','response-empty',L('조건에 맞는 정책을 찾지 못했습니다. 정책이 없다는 뜻은 아닙니다. 검색 조건을 바꾸거나 조사 질문으로 남겨 주세요.','No matching records were found. This does not establish that no policy exists. Change the filters or take the question forward.')));for(const r of rows){const card=make('article','response-policy-card'),shared=matches(r);card.append(make('h4','',policyTitle(r)),make('p','ds-muted',L('OECD 등록 상태: ','OECD inventory status: ')+r.status),make('p','response-clue',shared.length?L('연결 단서 · 공통 AI 원칙: ','Connection clue · shared AI principles: ')+shared.join(' · '):L('연결 단서 · 같은 국가에 등록됨. 사건과의 관련성은 원문 검토가 필요합니다.','Connection clue · registered in the same country. Relevance to this incident needs source review.')));const actions=make('div','response-card-actions');actions.append(button(L('정책 상세·원문 확인','Read policy details and sources'),()=>window.aiRiskPolicy.openRecord(r)),button(L('이 정책의 근거 살펴보기 ▶','Review evidence for this policy ▶'),()=>{chosen=r;stage=3;render();body.scrollTop=0},'journey-primary'));card.append(actions);list.append(card)}};input.oninput=()=>{query=input.value;renderRows()};renderRows();}
footer.append(button(L('정책을 아직 찾지 못했어요 · 질문으로 이어가기','I have not found a policy · continue with a question'),()=>{chosen=null;stage=3;render();body.scrollTop=0}));}
function renderGaps(){body.append(make('h3','',L('무엇을 더 확인해야 할까요?','What evidence do we still need?')));if(chosen){const c=make('section','response-context');c.append(make('h4','',policyTitle(chosen)),link(L('OECD 정책 원문','OECD policy source'),source(chosen)));body.append(c)}else body.append(make('p','response-empty',L('관련 정책을 아직 연결하지 못했습니다. 먼저 적용 가능한 정책을 찾는 것부터 함께 조사합니다.','No relevant policy has been connected yet. The inquiry starts by looking for an applicable policy.')));
body.append(make('p','ds-muted',L('아래는 확인할 질문입니다. 등록 상태나 분류만으로 실제 적용·집행·효과를 판단하지 않습니다. 함께 조사할 항목을 선택하세요.','These are questions to verify. Inventory labels alone do not establish coverage, enforcement or effectiveness. Select what to investigate.')));
for(const [key,ko,en,hint]of [['coverage','이 위험을 다루는가?','Does it cover this risk?',chosen?L('등록 유형: ','Registered category: ')+chosen.category:L('관련 정책 미연결','No policy connected')],['implementation','실제로 실행되고 있는가?','Is it being implemented?',chosen?L('등록 상태: ','Inventory status: ')+chosen.status:L('시행·집행 근거 미확인','Implementation evidence not verified')],['effect','대응 효과를 확인할 수 있는가?','Is there evidence of effectiveness?',L('평가·성과 자료 미확인','Evaluation and outcome evidence not verified')]]){const row=make('label','response-gap');const input=make('input');input.type='checkbox';input.checked=checks.has(key);input.onchange=()=>{input.checked?checks.add(key):checks.delete(key);footer.querySelector('.journey-primary').disabled=!checks.size};const text=make('span');text.append(make('strong','',L(ko,en)),make('span','ds-muted',hint),make('span','',L('원문과 추가 근거 검토 필요','Source and supporting evidence need review')));row.append(input,text);body.append(row)}footer.append(button(L('◀ 정책 선택으로','◀ Back to policies'),()=>{stage=2;render();body.scrollTop=0}),button(L('선택한 질문으로 함께 조사하기 ▶','Investigate these questions together ▶'),handoff,'journey-primary'));footer.querySelector('.journey-primary').disabled=!checks.size;}
function handoff(){const selected=[...checks],isKo=window.aiRiskI18n?.language==='ko';const question=(chosen?'':L('이 사건에 적용할 수 있는 정책은 무엇인가요?\n','Which policies could apply to this incident?\n'))+selected.map(k=>'• '+questions[k][isKo?0:1]).join('\n');const note=[L('사건: ','Incident: ')+incident.title,incidentUrl(),chosen?L('검토할 정책 후보: ','Policy candidate to review: ')+policyTitle(chosen):L('관련 정책 미연결 · 정책 부재를 뜻하지 않습니다.','No policy connected; this does not mean no policy exists.'),chosen?source(chosen):'',L('적용·집행·효과는 아직 검증하지 않았습니다.','Coverage, implementation and effectiveness have not yet been verified.')].filter(Boolean).join('\n');const review={policyId:chosen?.id||null,policyTitle:chosen?policyTitle(chosen):null,policySource:chosen?source(chosen):null,incidentSource:incidentUrl(),sharedPrinciples:chosen?matches(chosen):[],questions:selected,assessment:'unverified',createdAt:new Date().toISOString()};returnFocus=null;dialog.close();document.dispatchEvent(new CustomEvent('risk:review',{detail:{...incident,policyReview:review,suggestedQuestion:question,suggestedNote:note}}));}
document.addEventListener('risk:policy-review',e=>{incident=e.detail;chosen=null;stage=2;query='';filter='all';checks.clear();['coverage','implementation','effect'].forEach(k=>checks.add(k));returnFocus=document.getElementById('explore-open');render();dialog.showModal();close.focus()});document.addEventListener('policy:loaded',()=>{if(dialog.open&&stage===2)render()});document.addEventListener('gis:country-selected',()=>{if(dialog.open){returnFocus=null;dialog.close()}incident=null;chosen=null});let lang=document.documentElement.lang;new MutationObserver(()=>{if(lang===document.documentElement.lang)return;lang=document.documentElement.lang;if(dialog.open)render()}).observe(document.documentElement,{attributes:true,attributeFilter:['lang']});
})();
