'use strict';
(()=>{
const $=id=>document.getElementById(id),make=(tag,cls,text)=>{const e=document.createElement(tag);if(cls)e.className=cls;if(text!==undefined)e.textContent=text;return e};
let context=null,active=null,items=[],saved=true;const key='ai-risk-local-inquiries-v1';
try{const v=JSON.parse(localStorage.getItem(key)||'[]');if(Array.isArray(v))items=v.filter(x=>x&&typeof x.id==='string'&&typeof x.topic==='string'&&typeof x.question==='string'&&Number.isInteger(x.stage)&&x.stage>=1&&x.stage<=3).slice(0,100)}catch{}
function persist(){try{localStorage.setItem(key,JSON.stringify(items));saved=true}catch{saved=false}return saved}
function reveal(id){const el=$(id);const section=el?.closest('#work-contribute,#work-results,#work-communities');for(const key of ['work-contribute','work-results','work-communities'])if($(key))$(key).hidden=!section||section.id!==key;const start=$('work-current');if(start)start.hidden=Boolean(section);const back=$('journey-back');if(back)back.hidden=!section;return el}
function go(id,fromHistory=false){const actual=id==='collective-work'?'work-current':id;const el=reveal(actual);if(!el)return;const section=el.closest('#work-contribute,#work-results,#work-communities');const header=$('collective-work').querySelector('.work-header');header.hidden=Boolean(section);const bar=$('workspace-nav');if(bar)bar.hidden=actual==='observatory';if(!fromHistory&&location.hash!=='#'+actual)history.pushState({caseId:active},'','#'+actual);requestAnimationFrame(()=>{const target=section?$('workspace-nav'):el;target?.scrollIntoView({behavior:'instant'});el.tabIndex=-1;el.focus({preventScroll:true});});}

function download(value){const u=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json;charset=utf-8'}));const a=make('a');a.href=u;a.download='ai-risk-inquiry.json';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}
const start=$('work-current');start.innerHTML='<div class="start-intro"><h2>어디에서 시작할까요?</h2><p>사건을 찾아 질문을 남기거나, 이미 가진 질문으로 시작하세요.</p></div><div class="journey-start-options"><button id="work-explore" class="journey-start-card"><span class="eyebrow">사건에서 시작</span><strong>관심 있는 사건 찾아보기 ▶</strong><span>국가와 분야를 고르고, 관련 정보와 질문을 남겨 보세요.</span></button><button id="start-question" class="journey-start-card"><span class="eyebrow">내 경험에서 시작</span><strong>이미 가진 질문 남기기 ▶</strong><span>내가 겪은 변화나 읽은 자료에서 떠오른 질문을 남겨 보세요.</span></button></div><button id="resume-questions" class="work-action">내 기록 이어보기 ▶</button>';
const back=make('button','work-action','◀ 함께하는 일로');back.id='journey-back';back.hidden=true;back.onclick=()=>go('collective-work');const workspaceNav=make('div','workspace-nav');workspaceNav.id='workspace-nav';const mapBack=make('button','work-action','▲ 지도에서 사건 보기');mapBack.onclick=()=>go('observatory');workspaceNav.append(back,mapBack);$('collective-work').prepend(workspaceNav);for(const link of $('collective-work').querySelectorAll('.work-header>a,.work-footer'))link.remove();
$('start-question').onclick=()=>go('work-contribute');$('resume-questions').onclick=()=>go('work-results');
const introParagraph=$('collective-work').querySelector('.work-header>div>p:not(.eyebrow)');if(introParagraph)introParagraph.remove();const footer=$('collective-work').querySelector('.work-footer>span');if(footer)footer.remove();const path=$('collective-work').querySelector('.work-path');if(path)path.remove();const state=$('collective-work').querySelector('.work-state');if(state)state.remove();
$('community-open').onclick=()=>go('collective-work');
function explore(){if($('risk-data').hidden){go('observatory');$('risk-state').textContent='지도에서 국가를 선택하고 AIM 조회가 끝나면 사건을 살펴볼 수 있습니다.';return}$('explore-open').click()}
$('work-explore').onclick=explore;
const results=$('work-results');results.innerHTML='<div class="work-section-heading"><h2>내 질문과 검토 기록</h2></div><p class="journey-disclosure">이 브라우저에 저장한 개인 기록입니다. 운영자에게 전송되거나 다른 사람에게 공개되지 않습니다.</p><div id="case-list"></div><section id="case-workspace" hidden></section>';
const contribute=$('work-contribute');contribute.innerHTML='<div class="work-section-heading"><h2>내가 아는 정보·질문 보태기</h2><p>확인한 사실 하나, 함께 풀고 싶은 질문 하나부터.</p></div><div id="inquiry-context" class="inquiry-context"></div><form id="inquiry-form" class="flow-form"><label for="inquiry-topic">함께 살펴볼 주제</label><input id="inquiry-topic" maxlength="300" required><label for="inquiry-source">관련 출처 주소</label><input id="inquiry-source" type="url" maxlength="2000" placeholder="https://"><label for="inquiry-note">내가 아는 정보</label><textarea id="inquiry-note" rows="3" maxlength="6000" placeholder="경험이나 추가 자료를 남겨 주세요."></textarea><label for="inquiry-question">함께 확인하고 싶은 질문</label><textarea id="inquiry-question" rows="3" maxlength="3000" required></textarea><button class="journey-primary">질문 기록하고 다음 단계 보기</button><p id="inquiry-status" role="status"></p><small>기록은 이 브라우저에 저장됩니다. 온라인 제출과 조사 의뢰는 준비 중입니다.</small></form>';
function renderContext(){const box=$('inquiry-context');box.replaceChildren();if(context){box.append(make('span','state-badge available',context.country?.name||'선택한 사건'),Object.assign(make('strong','',context.title),{translate:context.id?'no':'yes'}));}else box.append(make('p','','사건을 고르면 국가·주제·출처가 자동으로 연결됩니다. 직접 주제를 적어도 됩니다.'));const btn=make('button','work-action',context?'다른 사건 살펴보기':'관심 분야에서 사건 찾기');btn.type='button';btn.onclick=explore;box.append(btn);if(context?.policyReview){box.prepend(make('p','eyebrow','04 · 함께 조사하기'));box.append(make('p','',context.policyReview.policyTitle||'정책 연결을 아직 확인하지 못했습니다.'))}}renderContext();
document.addEventListener('risk:review',e=>{const record=e.detail;if($('inquiry-question').value.trim()||$('inquiry-note').value.trim()){$('inquiry-status').textContent='작성 중인 질문을 유지했습니다. 먼저 기록한 뒤 다른 사건을 선택해 주세요.';go('work-contribute');return}context=record;$('inquiry-topic').value=(record.id?record.title:(window.aiRiskI18n?.t(record.title)||record.title)).slice(0,300);$('inquiry-source').value=record.id?'https://oecd.ai/en/incidents/'+encodeURIComponent(record.id):(record.sourceUrl||'');if(record.suggestedQuestion)$('inquiry-question').value=record.suggestedQuestion.slice(0,3000);if(record.suggestedNote)$('inquiry-note').value=record.suggestedNote.slice(0,6000);renderContext();go('work-contribute');$('inquiry-question').focus({preventScroll:true})});
$('inquiry-form').onsubmit=e=>{e.preventDefault();const topic=$('inquiry-topic').value.trim(),question=$('inquiry-question').value.trim();if(!topic||!question){$('inquiry-status').textContent='주제와 질문을 입력해 주세요.';return}if(items.length>=100){$('inquiry-status').textContent='개인 기록은 최대 100개입니다. 보관한 기록을 정리한 뒤 다시 시도해 주세요.';return}const c={id:crypto.randomUUID(),topic,question,source:$('inquiry-source').value.trim(),note:$('inquiry-note').value.trim(),country:context?.country||null,eventId:context?.id||null,policyReview:context?.policyReview||null,tags:context?.properties||{},stage:1,research:'',evidence:'',proposal:'',audience:'',createdAt:new Date().toISOString()};items.unshift(c);persist();$('inquiry-form').reset();context=null;renderContext();renderList();openCase(c.id);go('case-workspace')};
const stageNames=['','질문 기록','조사 메모 작성','논의안 작성'];
function renderList(){const list=$('case-list');const resume=$('resume-questions');if(resume)resume.classList.toggle('work-secondary',items.length>0);if(resume)resume.textContent=items.length?'내 기록 '+items.length+'개 이어보기 ▶':'남긴 질문과 검토 과정 살펴보기 ▶';list.replaceChildren();if(!items.length){const empty=make('div','result-note');empty.append(make('p','','아직 남긴 질문이 없습니다.'),make('span','','질문을 남기면 이곳에서 근거를 모으고 논의안을 다듬을 수 있습니다.'));const b=make('button','work-action','관심 분야에서 사건 찾기');b.onclick=explore;empty.append(b);list.append(empty);return}for(const c of items){const row=make('article','case-row');row.append(make('span','state-badge preparing','개인 기록 · '+stageNames[c.stage]),make('h3','',c.topic),make('p','',c.question));const b=make('button','work-action work-secondary','이 기록 이어보기 ▶');b.onclick=()=>{openCase(c.id);go('case-workspace')};row.append(b);list.append(row)}}
function openCase(id){active=id;reveal('case-workspace');const c=items.find(x=>x.id===id);if(!c)return;const box=$('case-workspace');box.hidden=false;box.replaceChildren();const head=make('header','case-heading');head.append(make('span','eyebrow',c.country?.name||'직접 남긴 주제'),make('h3','',c.topic),make('p','',c.question));box.append(head);const notice=make('p','journey-disclosure',saved?'이 브라우저에 저장된 개인 기록 · 조사 메모와 논의안을 저장하며 다음 단계로 이어가세요.':'브라우저 저장에 실패했습니다. 화면을 떠나기 전에 기록을 내려받아 주세요.');box.append(notice);$('case-list').hidden=true;const all=make('button','work-action','◀ 내 기록 목록');all.onclick=()=>{box.hidden=true;$('case-list').hidden=false;go('work-results')};box.append(all);const nav=make('div','case-tabs');for(const [num,label]of [[1,'남긴 질문'],[2,'조사 메모'],[3,'정책 논의안']]){const b=make('button','classification-chip',label);b.setAttribute('aria-pressed',String(num===c.stage));b.onclick=()=>renderStage(c,num);nav.append(b)}box.append(nav);box.append(make('div','case-stage'));const bar=make('div','case-actions');const exportBtn=make('button','work-action','기록 내려받기');exportBtn.onclick=()=>download(c);bar.append(exportBtn);const remove=make('button','work-action','개인 기록 삭제');let confirming=false;remove.onclick=()=>{if(!confirming){confirming=true;remove.textContent='정말 삭제하기';return}items=items.filter(x=>x.id!==c.id);persist();active=null;box.hidden=true;$('case-list').hidden=false;renderList();renderCommunity(null);go('work-results')};bar.append(remove);box.append(bar);renderStage(c,c.stage===1?1:c.stage)}
function renderStage(c,stage){const target=$('case-workspace').querySelector('.case-stage');target.replaceChildren();for(const [i,b]of [...$('case-workspace').querySelectorAll('.case-tabs button')].entries())b.setAttribute('aria-pressed',String(i+1===stage));if(stage===1){target.append(make('h4','','내가 남긴 정보와 질문'),make('p','case-text',c.note||'추가 정보 없이 질문을 남겼습니다.'));if(c.source&&/^https?:\/\//i.test(c.source)){const link=make('a','journey-link work-source-link','출처 원문 보기');link.href=c.source;link.target='_blank';link.rel='noopener';target.append(link)}target.append(make('p','','확인한 사실과 아직 모르는 점을 구분해 조사 메모를 남겨 보세요.'));const b=make('button','journey-primary','조사 메모 작성하기 ▶');b.onclick=()=>renderStage(c,2);target.append(b);return}
const form=make('form','flow-form');const fields=stage===2?[['research','확인한 사실과 더 확인할 점',c.research],['evidence','검토한 출처·확인 날짜',c.evidence]]:[['proposal','함께 논의할 정책 질문과 대응 제안',c.proposal]];
if(stage===3&&!c.research){target.append(make('p','','논의안을 만들기 전에 조사 근거부터 남겨 주세요.'));const b=make('button','journey-primary','조사 메모로 이동');b.onclick=()=>renderStage(c,2);target.append(b);return}
for(const [name,label,value]of fields){const lab=make('label','',label),input=make('textarea');input.id='case-'+name;input.name=name;input.rows=4;input.maxLength=6000;input.required=true;input.value=value||'';lab.htmlFor=input.id;form.append(lab,input)}const submit=make('button','journey-primary',stage===2?'조사 메모 저장하고 논의안 만들기 ▶':'논의안 저장하고 논의 분야 보기 ▶');form.append(submit);form.onsubmit=e=>{e.preventDefault();for(const [name]of fields){const v=form.elements[name].value.trim();if(!v){form.elements[name].focus();return}c[name]=v}c.stage=stage;c.updatedAt=new Date().toISOString();persist();renderList();openCase(c.id);if(stage===2)renderStage(c,3);else{renderCommunity(c);go('work-communities')}};target.append(make('p','journey-disclosure',stage===2?'직접 확인한 내용과 출처를 남겨 주세요. 운영자의 검증을 거친 기록은 아닙니다.':'확인한 근거를 바탕으로 함께 논의할 질문과 대응 방안을 적어 보세요.'),form)}
const directory=make('section','work-section');directory.id='work-communities';directory.innerHTML='<div class="work-section-heading"><h2>어떤 사람들과 함께 풀어갈까요?</h2><p>이 질문을 풀어가는 데 어떤 경험과 전문성이 필요할지 살펴보세요.</p></div><p class="journey-disclosure">함께 논의할 분야를 고르고 기록을 내려받을 수 있습니다. 실제 단체 검색과 연락 기능은 준비 중입니다.</p><div id="community-context"></div><div id="community-fields" class="work-grid"></div><p id="community-status" role="status"></p>';$('collective-work').append(directory);
const groups=[['rights','권리·시민사회','피해 당사자의 경험, 개인정보와 권리 보호를 함께 살펴볼 분야'],['technology','기술·연구','기술적 원인과 근거, 재현 가능성을 함께 검토할 분야'],['policy','정책·지역사회','제도의 적용 범위와 국가별 차이를 함께 논의할 분야']];
function renderCommunity(c){$('community-context').replaceChildren();if(c){$('community-context').append(make('h3','',c.topic),make('p','case-text',c.proposal||c.question));}else{const message=make('p','','먼저 논의할 질문이나 검토 기록을 선택해 주세요.');const resume=make('button','journey-primary',items.length?'내 기록에서 선택하기':'사건에서 질문 시작하기');resume.onclick=()=>{if(items.length){$('case-list').hidden=false;$('case-workspace').hidden=true;go('work-results')}else explore()};$('community-context').append(message,resume)}$('community-fields').replaceChildren();if(!c)return;for(const [id,title,desc]of groups){const card=make('article','work-card');card.append(make('h3','',title),make('p','',desc));if(c){const tags=Object.values(c.tags||{}).flat().join(' ').toLowerCase();const clue=id==='rights'&&/rights|privacy|consumers|workers|children|women/.test(tags)?'선택한 사건에 권리·피해 대상 분류가 있습니다.':id==='technology'&&/security|recognition|generation|detection|prediction/.test(tags)?'선택한 사건에 기술·AI 작업 분류가 있습니다.':null;if(clue)card.append(make('p','community-clue',clue));}const b=make('button','work-action',c?'이 분야에 공유할 초안 내려받기':'이 분야에서 질문 시작하기');b.onclick=()=>{if(!c){go('work-contribute');$('inquiry-question').focus({preventScroll:true});return}c.audience=title;persist();download({...c,sharingNote:window.aiRiskI18n?.t('이 자료는 개인 논의 초안입니다. 아직 단체에 전달되지 않았습니다.')||'이 자료는 개인 논의 초안입니다. 아직 단체에 전달되지 않았습니다.'});$('community-status').textContent=title+' 분야에 공유할 초안의 다운로드를 요청했습니다. 단체에 자동 전송되지는 않습니다.'};card.append(b);$('community-fields').append(card)}}
for(const link of document.querySelectorAll('[data-review-task]'))link.onclick=e=>{e.preventDefault();const mode=link.dataset.reviewTask;if(mode==='source')explore();else if(mode==='policy'){$('case-list').hidden=false;$('case-workspace').hidden=true;go('work-results');}else{renderCommunity(active?items.find(x=>x.id===active):null);go('work-communities')}};
renderList();renderCommunity(null);
for(const link of $('collective-work').querySelectorAll('a[href="#work-communities"]'))link.addEventListener('click',e=>{e.preventDefault();renderCommunity(active?items.find(x=>x.id===active):null);go('work-communities')});
$('resume-questions').onclick=()=>{$('case-list').hidden=false;$('case-workspace').hidden=true;go('work-results')};
function restoreRoute(){const id=location.hash.slice(1);if(id==='case-workspace'){const recordId=history.state?.caseId;if(recordId&&items.some(c=>c.id===recordId)){openCase(recordId);go(id,true)}else{$('case-list').hidden=false;$('case-workspace').hidden=true;go('work-results',true)}}else if(['work-current','collective-work','work-contribute','work-results','work-communities','observatory'].includes(id)){if(id==='work-results'){$('case-list').hidden=false;$('case-workspace').hidden=true}if(id==='work-communities')renderCommunity(active?items.find(c=>c.id===active):null);go(id,true)}else{reveal('work-current');$('collective-work').querySelector('.work-header').hidden=false;}}
window.addEventListener('popstate',restoreRoute);window.addEventListener('hashchange',restoreRoute);restoreRoute();
})();
