const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),{spawn}=require('node:child_process');
const root=path.resolve(__dirname,'..');
(async()=>{const port=await new Promise(r=>{const s=require('node:net').createServer();s.listen(0,'127.0.0.1',()=>{const p=s.address().port;s.close(()=>r(p));});});const server=spawn(process.execPath,['server.cjs','--dist'],{cwd:root,env:{...process.env,PORT:String(port)},stdio:['ignore','pipe','pipe'],windowsHide:true});let browser;
try{await new Promise(r=>server.stdout.once('data',r));browser=await chromium.launch({channel:process.platform==='win32'?'msedge':undefined,headless:true});const page=await browser.newPage({viewport:{width:1280,height:900}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
const doc={question:'Fixture weekly question',items:['risk','policy'].flatMap(kind=>Array.from({length:10},(_,i)=>({id:kind+i,kind,title:kind+' issue '+i,change:'Evidence checked',risk:'Risk analysis',policy:'Policy analysis',signal:'Next week signal',reason:'Editorial reasoning',source:'https://example.com/source',reviewed:true})))};let state={week_start:'2026-09-28',revision:'r1',draft:structuredClone(doc),published:null,candidates:[],collection:{}},pub=null,saves=0;
const id='11111111-1111-4111-8111-111111111111',jwt=[Buffer.from('{"alg":"HS256"}').toString('base64url'),Buffer.from(JSON.stringify({sub:id,exp:Math.floor(Date.now()/1000)+3600,role:'authenticated'})).toString('base64url'),'test'].join('.'),user={id,email:'admin@example.com',role:'authenticated',aud:'authenticated'};
await page.addInitScript(({jwt,user})=>sessionStorage.setItem('airisk-ontology-admin',JSON.stringify({access_token:jwt,refresh_token:'fixture',expires_at:Math.floor(Date.now()/1000)+3600,user})),{jwt,user});
await page.route('https://**',r=>r.abort());await page.route('https://*.supabase.co/**',async r=>{const url=r.request().url(),body=r.request().postDataJSON();let data;
if(url.includes('/auth/v1/user'))data=user;
else if(url.endsWith('airisk_ontology_state')){const o=JSON.parse(fs.readFileSync(path.join(root,'ontology.json')));data={revision:'o1',draft:o,published:o,history:[]};}
else if(url.endsWith('airisk_weekly_state'))data=state;
else if(url.endsWith('airisk_weekly_save')){state={...state,draft:body.document,revision:'r'+(++saves+1)};data=state;}
else if(url.endsWith('airisk_weekly_publish')){state={...state,published:structuredClone(state.draft),revision:'p1'};data=state;pub={week_start:'2026-09-28',week_end:'2026-10-04',published_at:'2026-10-05T00:00:00Z',document:state.published};}
else if(url.endsWith('airisk_weekly_public'))data=pub;else return r.fulfill({status:404,json:{message:'Not mocked'}});return r.fulfill({json:data});});
const base='http://127.0.0.1:'+port;await page.goto(base+'/admin/');await page.locator('#editor').waitFor({state:'visible'});await page.locator('#weekly-workspace-tab').click();const frame=page.frameLocator('#weekly-frame');await frame.locator('#weekly-editor').waitFor({state:'visible'});await frame.locator('#selected article button').first().click();await frame.locator('#weekly-field-change').fill('Edited reviewed finding');assert(await frame.locator('#publish').isDisabled());
await page.locator('#ontology-workspace-tab').click();await page.locator('#weekly-workspace-tab').click();assert.equal(await frame.locator('#weekly-field-change').inputValue(),'Edited reviewed finding');await frame.locator('#reviewed').check();await frame.locator('#save').click();await frame.locator('#publish:not([disabled])').waitFor();assert.equal(saves,1);await frame.locator('#publish').click();await frame.locator('#weekly-confirm').waitFor({state:'visible'});await frame.locator('#accept').click();await frame.locator('#weekly-message').filter({hasText:'공개 발행'}).waitFor();
await page.route(base+'/weekly-fixture',r=>r.fulfill({contentType:'text/html',body:'<!doctype html><html lang="ko"><head><meta charset="utf-8"><link rel="stylesheet" href="/design-system.css"><link rel="stylesheet" href="/journey.css"><link rel="stylesheet" href="/weekly-briefing.css"></head><body><div class="map-controls"></div><script src="/weekly-model.js"></script><script src="/weekly-briefing.js"></script></body></html>'}));
await page.goto(base+'/weekly-fixture');await page.locator('#weekly-dialog').waitFor({state:'visible'});assert.equal(await page.locator('#weekly-panel details').count(),10);await page.locator('#weekly-tab-policy').click();assert((await page.locator('#weekly-panel summary').first().textContent()).includes('policy issue'));await page.locator('#weekly-panel summary').first().click();assert((await page.locator('#weekly-panel').textContent()).includes('Next week signal'));
await page.keyboard.press('Escape');assert(await page.locator('#weekly-dialog').isVisible());for(const width of [390,320]){await page.setViewportSize({width,height:850});const rect=await page.locator('#weekly-dialog').boundingBox();assert(rect.x>=0&&rect.x+rect.width<=width+1);}
await page.locator('#weekly-dialog .journey-close').click();await page.reload();await page.waitForTimeout(300);assert(!await page.locator('#weekly-dialog').isVisible());await page.locator('#weekly-open').click();assert(await page.locator('#weekly-dialog').isVisible());for(const kind of ['risk','policy']){pub={...pub,published_at:kind==='risk'?'2026-10-05T01:00:00Z':'2026-10-05T02:00:00Z',document:{...doc,items:doc.items.filter(x=>x.kind===kind).slice(0,1)}};await page.reload();await page.locator('#weekly-dialog').waitFor({state:'visible'});await page.locator('#weekly-tab-'+kind).click();assert.equal(await page.locator('#weekly-panel details').count(),1);assert((await page.locator('#weekly-tab-'+kind).textContent()).includes('1'));await page.locator('#weekly-tab-'+(kind==='risk'?'policy':'risk')).click();assert.equal(await page.locator('#weekly-panel details').count(),0);assert((await page.locator('#weekly-panel').textContent()).includes('이번 주 이 분야의 선정 이슈는 없습니다'),await page.locator('#weekly-panel').textContent());}assert.deepEqual(errors,[]);console.log('PASS weekly UI: embedded admin tab retains edits; save/review/publish; public RISK/POLICY TOP 10; dismissal and mobile bounds.');
}finally{await browser?.close();server.kill();}})().catch(e=>{console.error(e);process.exitCode=1});
