const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),{spawn}=require('node:child_process');
const root=path.resolve(__dirname,'..');fs.mkdirSync(path.join(root,'output'),{recursive:true});
async function targets(scope){const violations=await scope.evaluateAll(els=>els.filter(e=>e.getClientRects().length&&!e.disabled).flatMap(e=>{const r=e.getBoundingClientRect(),c=getComputedStyle(e);return r.height<43.9||parseFloat(c.fontSize)<14?[{text:e.textContent.slice(0,40),height:r.height,font:c.fontSize}]:[]}));assert.deepEqual(violations,[]);}
async function noOverflow(scope){assert(await scope.evaluate(e=>e.scrollWidth<=e.clientWidth),'No horizontal overflow');}
(async()=>{const port=await new Promise(r=>{const s=require('node:net').createServer();s.listen(0,'127.0.0.1',()=>{const p=s.address().port;s.close(()=>r(p));});});const server=spawn(process.execPath,['server.cjs','--dist'],{cwd:root,env:{...process.env,PORT:String(port)},stdio:['ignore','pipe','pipe'],windowsHide:true});let browser;
try{await new Promise(r=>server.stdout.once('data',r));browser=await chromium.launch({channel:process.platform==='win32'?'msedge':undefined,headless:true});const page=await browser.newPage({viewport:{width:1280,height:900}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
const doc={question:'Fixture weekly question',items:['risk','policy'].flatMap(kind=>Array.from({length:10},(_,i)=>({id:kind+i,kind,title:kind+' issue '+i,change:'Evidence checked',risk:'Risk analysis',policy:'Policy analysis',signal:'Next week signal',reason:'Editorial reasoning',source:'https://example.com/source',reviewed:true})))};let state={week_start:'2026-09-28',revision:'r1',draft:structuredClone(doc),published:null,candidates:[{kind:'risk',id:'candidate',title:'Candidate for review',date:'2026-09-30',summary:'Original summary',source:'https://example.com'}],collection:{}},pub=null,saves=0,aiState=null,aiCalls=[],proposalEmpty=false;
const id='11111111-1111-4111-8111-111111111111',jwt=[Buffer.from('{"alg":"HS256"}').toString('base64url'),Buffer.from(JSON.stringify({sub:id,exp:Math.floor(Date.now()/1000)+3600,role:'authenticated'})).toString('base64url'),'test'].join('.'),user={id,email:'admin@example.com',role:'authenticated',aud:'authenticated'};
await page.addInitScript(({jwt,user})=>sessionStorage.setItem('airisk-ontology-admin',JSON.stringify({access_token:jwt,refresh_token:'fixture',expires_at:Math.floor(Date.now()/1000)+3600,user})),{jwt,user});
await page.route('https://**',r=>r.abort());await page.route('https://*.supabase.co/**',async r=>{const url=r.request().url(),body=r.request().postDataJSON();let data;
if(url.includes('/auth/v1/user'))data=user;
else if(url.endsWith('airisk_weekly_ai_state'))data=aiState;
else if(url.endsWith('/functions/v1/weekly-ai-settings')){aiCalls.push(body);if(body.action==='generate')data={week_revision:state.revision,proposal:{question:state.draft.question,note:'관련 후보만 선정',items:proposalEmpty?[]:[{...doc.items[0],id:'candidate',title:'Candidate for review',reviewed:false}]}};else if(body.action==='models')data={models:['example-model'],partial:false};else if(body.action==='test')data={verified:true};else if(body.action==='delete'){aiState=null;data={state:null};}else{aiState={provider:body.provider,model:body.model,revision:'ai-r1',updated_at:'2026-10-05T00:00:00Z',key_registered:true};data={state:aiState};}}

else if(url.endsWith('airisk_ontology_state')){const o=JSON.parse(fs.readFileSync(path.join(root,'ontology.json')));data={revision:'o1',draft:o,published:o,history:[]};}
else if(url.endsWith('airisk_weekly_state'))data=state;
else if(url.endsWith('airisk_weekly_save')){state={...state,draft:body.document,revision:'r'+(++saves+1)};data=state;}
else if(url.endsWith('airisk_weekly_publish')){state={...state,published:structuredClone(state.draft),revision:'p1'};data=state;pub={week_start:'2026-09-28',week_end:'2026-10-04',published_at:'2026-10-05T00:00:00Z',document:state.published};}
else if(url.endsWith('airisk_weekly_public'))data=pub;else return r.fulfill({status:404,json:{message:'Not mocked'}});return r.fulfill({json:data});});
const base='http://127.0.0.1:'+port;await page.goto(base+'/admin/');await page.locator('#editor').waitFor({state:'visible'});await page.locator('#weekly-workspace-tab').click();const frame=page.frameLocator('#weekly-frame');await frame.locator('#weekly-editor').waitFor({state:'visible'});await frame.locator('#ai-settings>summary').click();await frame.locator('#ai-status').filter({hasText:'서버 설정을 불러왔습니다'}).waitFor();await frame.locator('#ai-provider').selectOption('openai');await frame.locator('#ai-key').fill('fixture-key-secret');await frame.locator('#ai-models').click();await frame.locator('#ai-model-list option').waitFor();await frame.locator('#ai-model-list').selectOption('example-model');assert(await frame.locator('#ai-test').isDisabled());await frame.locator('#ai-save').click();await frame.locator('#ai-status').filter({hasText:'서버에 저장했습니다'}).waitFor();assert.equal(await frame.locator('#ai-key').inputValue(),'');assert(!await frame.locator('body').textContent().then(s=>s.includes('fixture-key-secret')));assert(await frame.locator('body').evaluate(()=>![...Object.values(localStorage),...Object.values(sessionStorage)].join('').includes('fixture-key-secret')));await frame.locator('#ai-test').click();await frame.locator('#ai-status').filter({hasText:'연결 확인 완료'}).waitFor();assert(!('key' in aiCalls.at(-1)));
for(const width of [1280,412,390,320]){await page.setViewportSize({width,height:width===412?914:900});await targets(frame.locator('#ai-settings button,#ai-settings a,#ai-settings input,#ai-settings select,#ai-settings summary'));await noOverflow(frame.locator('html'));await page.screenshot({path:path.join(root,'output/ai-settings-'+width+'.png')});}
await frame.locator('#ai-delete').click();assert(await frame.locator('#ai-cancel').evaluate(e=>e===document.activeElement));await page.keyboard.press('Escape');assert(await frame.locator('#ai-confirm').isVisible());await frame.locator('#ai-accept').click();await frame.locator('#ai-status').filter({hasText:'삭제했습니다'}).waitFor();assert.equal(aiState,null);await frame.locator('#ai-settings>summary').click();await page.setViewportSize({width:1280,height:900});await frame.locator('#selected article button').first().click();for(const width of [1280,412,390,320]){await page.setViewportSize({width,height:width===412?914:900});await targets(frame.locator('button,a,input:not([type=checkbox]),textarea,summary,.weekly-review'));await noOverflow(frame.locator('html'));assert.equal(await frame.locator('#reviewed').evaluate(e=>e.getBoundingClientRect().width),20);await page.screenshot({path:path.join(root,'output/weekly-admin-'+width+'.png')});}await page.setViewportSize({width:1280,height:900});await frame.locator('#weekly-field-change').fill('Edited reviewed finding');assert(await frame.locator('#publish').isDisabled());
await page.locator('#ontology-workspace-tab').click();await page.locator('#weekly-workspace-tab').click();assert.equal(await frame.locator('#weekly-field-change').inputValue(),'Edited reviewed finding');await frame.locator('#reviewed').check();await frame.locator('#save').click();await frame.locator('#publish:not([disabled])').waitFor();assert.equal(saves,1);await frame.locator('#publish').click();await frame.locator('#weekly-confirm').waitFor({state:'visible'});assert.equal(await frame.locator('#weekly-confirm').getAttribute('aria-labelledby'),'weekly-confirm-title');assert(await frame.locator('#cancel').evaluate(e=>e===document.activeElement));await page.keyboard.press('Escape');assert(await frame.locator('#weekly-confirm').isVisible());await frame.locator('#accept').click();await frame.locator('#weekly-message').filter({hasText:'공개 발행'}).waitFor();
aiState={provider:'openai',model:'example-model',revision:'ai-r2'};await frame.locator('#ai-generate-weekly').click();await frame.locator('#ai-proposal').waitFor({state:'visible'});assert.equal(state.draft.items.length,20);assert.equal(pub.document.items.length,20);await frame.locator('#ai-apply-weekly').click();await frame.locator('#accept').click();await frame.locator('#weekly-message').filter({hasText:'편집 초안'}).waitFor();assert.equal(await frame.locator('#selected article').count(),1);await frame.locator('#selected article button').first().click();assert(!await frame.locator('#reviewed').isChecked());assert(await frame.locator('#publish').isDisabled());await frame.locator('#save').click();await frame.locator('#publish:not([disabled])').waitFor();assert.equal(state.draft.items.length,1);assert.equal(pub.document.items.length,20);
proposalEmpty=true;await frame.locator('#ai-generate-weekly').click();await frame.locator('#ai-proposal').waitFor({state:'visible'});assert(await frame.locator('#ai-apply-weekly').isDisabled());assert.equal(state.draft.items.length,1);await frame.locator('#ai-discard-weekly').click();

await page.route(base+'/weekly-fixture',r=>r.fulfill({contentType:'text/html',body:'<!doctype html><html lang="ko"><head><meta charset="utf-8"><link rel="stylesheet" href="/typography.css"><link rel="stylesheet" href="/design-system.css"><link rel="stylesheet" href="/journey.css"><link rel="stylesheet" href="/weekly-briefing.css"></head><body><div class="map-controls"></div><script src="/weekly-model.js"></script><script src="/weekly-briefing.js"></script></body></html>'}));
await page.goto(base+'/weekly-fixture');await page.locator('#weekly-dialog').waitFor({state:'visible'});assert.equal(await page.locator('#weekly-panel details').count(),10);await page.locator('#weekly-tab-policy').click();assert((await page.locator('#weekly-panel summary').first().textContent()).includes('policy issue'));await page.locator('#weekly-panel summary').first().click();assert((await page.locator('#weekly-panel').textContent()).includes('Next week signal'));
await page.keyboard.press('Escape');assert(await page.locator('#weekly-dialog').isVisible());for(const width of [1280,412,390,320])for(const lang of ['ko','en']){await page.evaluate(lang=>document.documentElement.lang=lang,lang);await page.locator('#weekly-panel summary').first().click();await targets(page.locator('#weekly-dialog button,#weekly-dialog a,#weekly-dialog summary'));assert.equal(await page.locator('#weekly-tab-policy').evaluate(e=>getComputedStyle(e).backgroundColor),'rgb(168, 221, 210)');await page.setViewportSize({width,height:width===412?914:850});const rect=await page.locator('#weekly-dialog').boundingBox();assert(rect.x>=0&&rect.x+rect.width<=width+1);await noOverflow(page.locator('#weekly-dialog'));await page.screenshot({path:path.join(root,'output/weekly-public-'+lang+'-'+width+'.png')});}await page.locator('#weekly-tab-policy').focus();await page.keyboard.press('Home');assert.equal(await page.locator('#weekly-tab-risk').getAttribute('aria-selected'),'true');assert(await page.locator('#weekly-tab-risk').evaluate(e=>e===document.activeElement));await page.keyboard.press('End');assert.equal(await page.locator('#weekly-tab-policy').getAttribute('aria-selected'),'true');
await page.locator('#weekly-dialog .journey-close').click();await page.reload();await page.waitForTimeout(300);assert(!await page.locator('#weekly-dialog').isVisible());await page.locator('#weekly-open').click();assert(await page.locator('#weekly-dialog').isVisible());for(const kind of ['risk','policy']){pub={...pub,published_at:kind==='risk'?'2026-10-05T01:00:00Z':'2026-10-05T02:00:00Z',document:{...doc,items:doc.items.filter(x=>x.kind===kind).slice(0,1)}};await page.reload();await page.locator('#weekly-dialog').waitFor({state:'visible'});await page.locator('#weekly-tab-'+kind).click();assert.equal(await page.locator('#weekly-panel details').count(),1);assert((await page.locator('#weekly-tab-'+kind).textContent()).includes('1'));await page.locator('#weekly-tab-'+(kind==='risk'?'policy':'risk')).click();assert.equal(await page.locator('#weekly-panel details').count(),0);assert((await page.locator('#weekly-panel').textContent()).includes('이번 주 이 분야의 선정 이슈는 없습니다'),await page.locator('#weekly-panel').textContent());}await page.locator('#weekly-dialog .journey-close').click();assert(await page.locator('#weekly-open').evaluate(e=>e===document.activeElement));pub=null;await page.reload();await page.locator('#weekly-open').click();await page.getByText('아직 발행된 주간 브리핑이 없습니다.',{exact:false}).waitFor();await page.route('**/rest/v1/rpc/airisk_weekly_public',r=>r.fulfill({status:503,json:{error:'fixture'}}));await page.reload();await page.locator('#weekly-open').click();await page.getByText('브리핑을 불러오지 못했습니다.',{exact:false}).waitFor();assert.deepEqual(errors,[]);console.log('PASS weekly UI: embedded admin tab retains edits; save/review/publish; public RISK/POLICY TOP 10; dismissal and mobile bounds.');
}finally{await browser?.close();server.kill();}})().catch(e=>{console.error(e);process.exitCode=1});
