const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),{PGlite}=require('@electric-sql/pglite');
test('national editions preserve Korea, isolate drafts/revisions/publication and never fall back across countries',async t=>{
 const db=new PGlite();t.after(()=>db.close());const admin='11111111-1111-4111-8111-111111111111';
 await db.exec(`create role anon;create role authenticated;create role service_role;create schema auth;create table auth.users(id uuid primary key);create function auth.uid() returns uuid language sql stable as $$ select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;create function auth.role() returns text language sql stable as $$ select current_setting('request.jwt.claim.role',true) $$;grant usage on schema public to anon,authenticated,service_role;insert into auth.users values('${admin}');`);
 const migration=file=>db.exec(fs.readFileSync(path.join(__dirname,'../supabase/migrations',file),'utf8'));
 for(const file of ['202610040001_ontology_admin.sql','202610050002_weekly_briefing.sql','202610050004_weekly_flexible_counts.sql'])await migration(file);
 await db.exec(`insert into airisk_private.ontology_admins(user_id) values('${admin}')`);
 const doc={question:'Korea fixture',items:[{id:'one',kind:'risk',title:'Fixture evidence',change:'Change',risk:'Risk',policy:'Policy',signal:'Signal',reason:'Reason',source:'https://example.com',reviewed:true}]};
 await db.query("insert into airisk_private.weekly_briefings(week_start,draft,published,published_at) values('2026-09-28',$1,$1,'2026-10-01')",[doc]);
 const before=(await db.query('select revision,published_at from airisk_private.weekly_briefings')).rows[0];
 await migration('202610050008_weekly_countries.sql');
 const role=async(name,id='')=>{await db.exec('reset role');await db.query("select set_config('request.jwt.claim.sub',$1,false),set_config('request.jwt.claim.role',$2,false)",[id,name]);await db.exec('set role '+name);};
 const rpc=async(name,values=[],types=[])=> (await db.query('select public.airisk_weekly_'+name+'('+values.map((_,i)=>'$'+(i+1)+'::'+types[i]).join(',')+') as result',values)).rows[0].result;
 await role('anon');assert.equal(await rpc('public'),null);
 for(const country of ['US','JP','ZZ',null,'kr',''])assert.equal(await rpc('public',[country],['text']),null);
 assert.deepEqual((await rpc('public',['KR'],['text'])).document,doc);
 await assert.rejects(rpc('state',['2026-09-28','US'],['date','text']),/permission denied/);
 await assert.rejects(db.exec('select * from airisk_private.weekly_candidate_batches'),/permission denied/);
 await role('authenticated',admin);
 let kr=await rpc('state',['2026-09-28','KR'],['date','text']);assert.equal(kr.revision,before.revision);assert.equal(new Date(kr.published_at).getTime(),new Date(before.published_at).getTime());
 let us=await rpc('state',['2026-09-28','US'],['date','text']);assert.deepEqual(us.draft,{question:'',items:[]});assert.equal(us.published,null);
 await assert.rejects(rpc('state',['2026-09-28',null],['date','text']),/Choose a country/);
 await assert.rejects(rpc('save',['2026-09-28',kr.revision,doc,'US'],['date','uuid','jsonb','text']),/Another editor/);
 const usDoc={...doc,question:'US fixture'};us=await rpc('save',['2026-09-28',us.revision,usDoc,'US'],['date','uuid','jsonb','text']);
 assert.equal(await rpc('public',['US'],['text']),null);
 us=await rpc('publish',['2026-09-28',us.revision,false,'US'],['date','uuid','boolean','text']);
 assert.deepEqual((await rpc('public',['US'],['text'])).document,usDoc);assert.deepEqual((await rpc('public',['KR'],['text'])).document,doc);
 await role('service_role');await rpc('ingest',['2026-09-28',[{id:'new-global-evidence'}],{source:'test'}],['date','jsonb','jsonb']);
 await role('authenticated',admin);
 for(const [code,saved] of [['KR',kr],['US',us]]){const current=await rpc('state',['2026-09-28',code],['date','text']);assert.equal(current.revision,saved.revision);assert.deepEqual(current.draft,saved.draft);assert.deepEqual(current.candidates,[{id:'new-global-evidence'}]);}
 await rpc('publish',['2026-09-28',us.revision,true,'US'],['date','uuid','boolean','text']);await role('anon');assert.equal(await rpc('public',['US'],['text']),null);assert.deepEqual((await rpc('public',['KR'],['text'])).document,doc);
});
